services:
  postgres:
    image: postgres:17.2
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
  crm-bl:
    image: rgombework/web-crm-bl
    environment:
      - KAFKA_HOST=kafka
      - KAFKA_PORT=29092
    restart: "always"
    ports:
      - "8081:8081"
    depends_on:
      - kafka
    labels:
      amplicode.image: springboot
  crm-dal:
    image: rgombework/web-crm-dal
    environment:
      - KAFKA_HOST=kafka
      - KAFKA_PORT=29092
      - POSTGRES_HOST=postgres
    restart: "always"
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - kafka
    labels:
      amplicode.image: springboot
  zookeeper:
    image: zookeeper:3.9.3
    restart: always
    ports:
      - "2181:2181"
    healthcheck:
      test: nc -z 127.0.0.1 2181 || exit -1
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
  kafka:
    image: confluentinc/cp-kafka:7.7.2
    restart: "no"
    ports:
      - "29092:29092"
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    healthcheck:
      test: kafka-topics --bootstrap-server localhost:29092 --list
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 5
    depends_on:
      - zookeeper
    labels:
      amplicode.image: confluent/kafka
volumes:
  kafka_data: